---
title: "MITable"
author: "Abigail McGrory"
date: "2024-11-04"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(here)
library(dplyr)
library(mice)
library(stargazer)
library(textreg)
library(here)
library(tidyverse)
library(kableExtra)
library(texreg)
library(plm)

finaldata <- read.csv("C:/Users/Abigail McGrory/Documents/PhD/First Year/Special Topics/armed_conflict/original/conflict_primary_analysis.csv")

finaldata$loggdp <- log(finaldata$gdp1000)

finaldata2 <- finaldata[complete.cases(finaldata[ , 13]),]

finaldata2[is.na(finaldata2)] <- 0


```

```{r, include=FALSE}

midata <- finaldata |>
  mutate(ISOnum = as.numeric(as.factor(finaldata$ISO))) |>
  select(-country_name, -ISO)


mice0  <- mice(midata, seed = 100, m = 5, maxit = 0, print = F)

meth <- mice0$method
meth[c("urban", "male_edu", "temp", "rainfall1000", "MatMor", "InfMor", "NeoMor", "UndMor", "loggdp", "popdens")] <- "2l.lmer"

pred <- mice0$predictorMatrix
pred[c("urban", "male_edu", "temp", "rainfall1000", "MatMor", "InfMor", "NeoMor", "UndMor", "loggdp", "popdens"), "ISOnum"] <- -2

mice.multi.out  <- mice(midata, seed = 100, m = 10, maxit = 10,
                        method = meth,
                        predictorMatrix = pred)


mice.matmod <- with(mice.multi.out, lm(MatMor ~ conflict + gdp1000 + OECD + popdens + urban + agedep + male_edu + temp + rainfall1000 + earthquake + drought))

mice.matmod.pool <- pool(mice.matmod)

matmod <- lm(MatMor ~ -1 + conflict + gdp1000 + OECD + popdens + urban + agedep + male_edu + temp + rainfall1000 + earthquake + drought,
              data = finaldata2)

matmod.sum <- summary(matmod)

mice.un5mod <- with(mice.multi.out, lm(UndMor ~ conflict + gdp1000 + OECD + popdens + urban + agedep + male_edu + temp + rainfall1000 + earthquake + drought))

mice.un5mod.pool <- pool(mice.un5mod)

un5mod <- lm(UndMor ~ -1 + conflict + gdp1000 + OECD + popdens + urban + agedep + male_edu + temp + rainfall1000 + earthquake + drought,
              data = finaldata2)

un5mod.sum <- summary(un5mod)

mice.infmod <- with(mice.multi.out, lm(InfMor ~ conflict + gdp1000 + OECD + popdens + urban + agedep + male_edu + temp + rainfall1000 + earthquake + drought))

mice.infmod.pool <- pool(mice.infmod)

infmod <- lm(InfMor ~ -1 + conflict + gdp1000 + OECD + popdens + urban + agedep + male_edu + temp + rainfall1000 + earthquake + drought,
              data = finaldata2)

infmod.sum <- summary(infmod)

mice.neomod <- with(mice.multi.out, lm(NeoMor ~ conflict + gdp1000 + OECD + popdens + urban + agedep + male_edu + temp + rainfall1000 + earthquake + drought))

mice.neomod.pool <- pool(mice.neomod)

neomod <- lm(NeoMor ~ -1 + conflict + gdp1000 + OECD + popdens + urban + agedep + male_edu + temp + rainfall1000 + earthquake + drought,
              data = finaldata2)

neomod.sum <- summary(neomod)


```

```{r, results='asis', echo=FALSE}
mods <- list(matmod, un5mod, infmod, neomod, summary(mice.matmod.pool), summary(mice.un5mod.pool), summary(mice.infmod.pool), summary(mice.neomod.pool))

keepvars <- list("conflict" = "Armed conflict",
                 "loggdp" = "log(GDP)",
                 "OECD" = "OECD",
                 "popdens" = "Population density",
                 "urban" = "Urban",
                 "agedep" = "Age dependency",
                 "male_edu" = "Male education",
                 "temp" = "Average temperature",
                 "rainfall" = "Average rainfall",
                 "earthquake" = "Earthquake",
                 "drought" = "Drought")
texreg(list(matmod, un5mod, infmod, neomod, mice.matmod.pool, mice.un5mod.pool, mice.infmod.pool, mice.neomod.pool), 
        ci.force = TRUE,
        custom.coef.map = keepvars,
        custom.model.names = c("Mat CC", "Mat MI", "Un5 CC", "Un5 MI", "Inf CC", "Inf MI", "Neo CC", "Neo MI"))

#stargazer(mods, type = "latex",dep.var.labels.include = FALSE,
          #covariate.labels = c("Armed Conflict", "logGDP",
          #"OECD", "Population Density", "Urban",
          #"Age Dependency", "Male Education",
          #"Average Temperature", "Earthquake",
          #"Drought"), dep.var.labels = c("Maternal Mortality",
          #"Under 5 Mortality", "Infant Mortality", 
          #"Neonatal Mortality"), out = "micemod.tex")
```
